### ISSUE TITLE
bonjourmadame--get-image-path: Invalid time specification

### ISSUE THREAD

**Issue by cvigano** [pierre-lecocq/bonjourmadame#1]
Using Emacs 24.5, I get this error message when trying to invoke bonjourmadame.

`float-time` seems to be deprecated in favor of `current-time` and if exchanged for the latter, the image is downloaded, but it is not shown in the buffer. The `current-time` format seems incompatible with the way you calculate the need for refreshing images.

**Comment by pierre-lecocq** [comment]
Hi !

Sorry for the delay. Just fixed.
Wait a few hour so that melpa reflect the change if you install the package through it.
